# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist|alembic)/
default_language_version:
  python: python3.11
default_stages: [pre-commit, pre-push]
repos:
  # https://github.com/pre-commit/pre-commit-hooks#pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
        -   --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # https://pycqa.github.io/isort/docs/configuration/pre-commit.html
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--config=pyproject.toml]
  # Check compliance with Ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        name: ruff (python)
        args : [--config=pyproject.toml]
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-jinja
        args: [--configuration=pyproject.toml]
      - id: djlint-jinja
