[tools]
ruff = "latest"
uv = "latest"
node = "latest"
prek = "latest"


[hooks]
preinstall = "echo 'I am about to install tools'"
postinstall = [
  "uv sync --all-groups --all-extras --reinstall",
  "npm install",
  "mise place-vendor",
]


[tasks.start]
description = "Run the Flask Application"
run = "flask run"


[tasks.install]
description = "Install the application dependencies"
hide = true
run = "uv sync --all-groups --all-extras --reinstall"


[tasks.place-vendor]
description = "Prepare the environment for development"
run = """
#!/usr/bin/env bash
SOURCE_BASE_PATH="node_modules"
TARGET_BASE_PATH="src/app/static/vendor"

echo - Copying HTMX
mkdir -p ${TARGET_BASE_PATH}/htmx
cp -a ${SOURCE_BASE_PATH}/htmx.org/dist/. ${TARGET_BASE_PATH}/htmx/

echo - Copying Bootstrap Show Password
mkdir -p ${TARGET_BASE_PATH}/bootstrap-show-password
cp -a ${SOURCE_BASE_PATH}/bootstrap-show-password/dist/. ${TARGET_BASE_PATH}/bootstrap-show-password/
"""


[tasks.lint]
description = "Run the linter"
run = """
#!/usr/bin/env bash
ruff check .
"""


[tasks.format]
description = "Run the formatter"
run = """
#!/usr/bin/env bash
ruff format .
"""


[tasks.test]
description = "Run the tests"
run = """
#!/usr/bin/env bash
pytest --tb=short --disable-warnings --maxfail=1
"""


[tasks.ci]
description = "Run the CI tasks"
depends = ["lint", "format", "test"]
